name: Notification on push

on: push
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Edit Files
      uses: TaiStudio/action-edit-YML@main
      with:
        who-to-greet: ['bonjour', 'comment', 'vas', 'tu', '?']
